### ISSUE TITLE
diff_kernel is not defined

### ISSUE THREAD

**Issue by BenoitSchillings** [JoshuaEbenezer/ftvd#2]
in getC, 

eigsDtD = np.abs(psf2otf(diff_kernel,sizeF))**2 + np.abs(psf2otf(diff_kernel,sizeF))**2 # Fourier transform of D transpose * D

is using diff_kernel which not defined anywhere.

**Comment by JoshuaEbenezer** [comment]
Thank you bringing this to my notice. I've corrected and updated the code.
