### ISSUE TITLE
Doubt in diff_kernel

### ISSUE THREAD

**Issue by nadr123** [JoshuaEbenezer/ftvd#4]
I have taken the image as grayscale not colored.

in getC,

diff_kernelX = np.expand_dims(np.array([1,-1]),axis=1)
Note- in above, array inside the np.expand_dims() is of dimension of (2, ) but after applying np.expand_dims() it will be of (2,1).
diff_kernelY = np.expand_dims(np.array([[1],[-1]]),axis=0)
Note- in above, array inside the np.expand_dims() is of dimension of (2, 1 ) but after applying np.expand_dims() it will be of (1, 2, 1). so this creates the problem in  the computation of psf2otf() in eigsDtD. More specifically, dshape will not be evaluated.

When I am taking the diff_kernelY = np.expand_dims(np.array([1,-1]),axis=0) then code works well but clean image is not obtained.

please check for diff_kernelY.

one more thing, what is the roll of the function fval(). you have commented on it in your code. so when I have executed the code in both cases(commented and uncommented situation), no effect will be observed.

**Comment by JoshuaEbenezer** [comment]
Hi
It's been a long time since I've written this so I don't remember the details. Please read the original MATLAB code written by the authors (not this code) to find out what each function and operation does.
