### ISSUE TITLE
MATLAB version of the code

### ISSUE THREAD

**Issue by swami1995** [JoshuaEbenezer/ftvd#5]
I tried using the repo with some greyscale images and my results don't seem great.  Do you know where I can find the MATLAB code for this repo? I couldn't find any links in the paper or any free versions through a simple google search? (I was only able to find a paid version through https://matlab1.com/shop/matlab-code/a-new-alternating-minimization-algorithm-for-total-variation-image-reconstruction/)

**Comment by JoshuaEbenezer** [comment]
I don't remember where I found the original code. Please look at each of the authors' websites. I think it's in one of their websites. You might have to change some hyperparameters for better results.
