### ISSUE TITLE
Denoising quality problematic

### ISSUE THREAD

**Issue by swami1995** [JoshuaEbenezer/ftvd#6]
For example I ran the code on the following image and got some pretty bad reconstructions.. 

![gs_2d_smoothing_noisy](https://user-images.githubusercontent.com/10100581/183111591-545226a1-e19e-4a32-8572-e5c873efa367.jpg)
![100_2d_smoothing_noisy](https://user-images.githubusercontent.com/10100581/183111589-b378e837-7224-41df-ab66-be9e22aa1f40.jpg)

**Comment by JoshuaEbenezer** [comment]
You might have to change some hyperparameters for better results.
